const CACHE_NAME = "duck-habit-hub-pwa-v24-19-paintable-lights";
const PRECACHE_URLS = [
  './',
  './assets/achievements/trophies/trophy-bronze.png',
  './assets/achievements/trophies/trophy-gold.png',
  './assets/achievements/trophies/trophy-rose-gold.png',
  './assets/achievements/trophies/trophy-silver.png',
  './apple-touch-icon-v2.png',
  './favicon-32-v2.png',
  './icon-192-v2.png',
  './icon-512-v2.png',
  './icon-maskable-512-v2.png',
  './assets/bakery/backgrounds/Bakery-background.PNG',
  './assets/bakery/drops/Gold-coin.PNG',
  './assets/bakery/drops/Gold-heart-refill.PNG',
  './assets/bakery/drops/Pink-heart-refill.PNG',
  './assets/bakery/drops/Rose-gold-coin.PNG',
  './assets/ducks/Alien-duck.PNG',
  './assets/ducks/angry-duck.png',
  './assets/ducks/apple-duck.png',
  './assets/ducks/bathtime-duck.png',
  './assets/ducks/duck-on-skateboard.png',
  './assets/ducks/googly-eye-duck.png',
  './assets/ducks/long-hair-duck.png',
  './assets/ducks/magenta-duck.png',
  './assets/ducks/pile-of-tiny-ducks.png',
  './assets/ducks/scarf-duck.png',
  './assets/ducks/vampire-duck.png',
  './assets/ducks/Angel-duck.PNG',
  './assets/ducks/Aqua-duck.PNG',
  './assets/ducks/Artist-duck.PNG',
  './assets/ducks/Black-duck.PNG',
  './assets/ducks/Blue-duck.PNG',
  './assets/ducks/Bow-duck.PNG',
  './assets/ducks/Bronze-duck.PNG',
  './assets/ducks/Bunny-duck.PNG',
  './assets/ducks/Burger-duck.PNG',
  './assets/ducks/Cat-duck.PNG',
  './assets/ducks/Cool-duck.PNG',
  './assets/ducks/Cosmic-duck.PNG',
  './assets/ducks/Cupcake-duck.PNG',
  './assets/ducks/Dark-red-duck.PNG',
  './assets/ducks/Demon-duck.PNG',
  './assets/ducks/Doctor-duck.PNG',
  './assets/ducks/Duck-with-a-knife.PNG',
  './assets/ducks/Duckvee.PNG',
  './assets/ducks/Fancy-duck.PNG',
  './assets/ducks/Flower-duck.PNG',
  './assets/ducks/Gamer-duck.PNG',
  './assets/ducks/Ghost-duck.PNG',
  './assets/ducks/Glitter-duck.PNG',
  './assets/ducks/Golden-duck.PNG',
  './assets/ducks/Goose.PNG',
  './assets/ducks/Green-duck.PNG',
  './assets/ducks/Grey-duck.PNG',
  './assets/ducks/Gummy-duck.PNG',
  './assets/ducks/Jester-duck.PNG',
  './assets/ducks/Kidcore-duck.PNG',
  './assets/ducks/King-duck.PNG',
  './assets/ducks/Knitted-duck.PNG',
  './assets/ducks/Lemon-duck.PNG',
  './assets/ducks/Lime-duck.PNG',
  './assets/ducks/Magical-girl-duck.PNG',
  './assets/ducks/Mint-duck.PNG',
  './assets/ducks/Mushroom-duck.PNG',
  './assets/ducks/Orange-duck.PNG',
  './assets/ducks/Party-hat-duck.PNG',
  './assets/ducks/Peach-duck.PNG',
  './assets/ducks/Periwinkle-duck.PNG',
  './assets/ducks/Pink-duck.PNG',
  './assets/ducks/Pizza-duck.PNG',
  './assets/ducks/Plush-duck.PNG',
  './assets/ducks/Pompompurin-duck.PNG',
  './assets/ducks/Purple-duck.PNG',
  './assets/ducks/Rainbow-duck.PNG',
  './assets/ducks/Red-duck.PNG',
  './assets/ducks/Silver-duck.PNG',
  './assets/ducks/Sky-blue-duck.PNG',
  './assets/ducks/Sleepy-time-duck.PNG',
  './assets/ducks/Standard-duck.PNG',
  './assets/ducks/Strawberry-duck.PNG',
  './assets/ducks/Tiny-duck-stack.PNG',
  './assets/ducks/Tiny-duck.PNG',
  './assets/ducks/Top-hat-duck.PNG',
  './assets/ducks/Violet-duck.PNG',
  './assets/ducks/Watermelon-duck.PNG',
  './assets/ducks/White-duck.PNG',
  './assets/food/Bread-loaf.PNG',
  './assets/food/apple.png',
  './assets/food/Burger.PNG',
  './assets/food/Cake-slice.PNG',
  './assets/food/Cake.PNG',
  './assets/food/Champagne.PNG',
  './assets/food/Chocolate-brioche.PNG',
  './assets/food/Concha.PNG',
  './assets/food/Cookie.PNG',
  './assets/food/Croissant.PNG',
  './assets/food/Cupcake.PNG',
  './assets/food/Fancy-milk-tea.PNG',
  './assets/food/Flour.PNG',
  './assets/food/Fruit-cup.PNG',
  './assets/food/Fruit-tart.PNG',
  './assets/food/Gummy-bear.PNG',
  './assets/food/Lemon.PNG',
  './assets/food/Lime.PNG',
  './assets/food/Lollipop.PNG',
  './assets/food/Milk-tea.PNG',
  './assets/food/Milk.PNG',
  './assets/food/Mushroom.PNG',
  './assets/food/Parfait.PNG',
  './assets/food/Pizza.PNG',
  './assets/food/Pudding.PNG',
  './assets/food/Strawberry-shortcake.PNG',
  './assets/food/Strawberry.PNG',
  './assets/food/Water.PNG',
  './assets/food/Watermelon.PNG',
  './assets/food/Wedding-cake.PNG',
  './assets/furniture/dressers/dresser-brown.png',
  './assets/furniture/dressers/dresser-dark-brown.png',
  './assets/furniture/pet-beds/petbed-blue.png',
  './assets/furniture/pet-beds/petbed-cream.png',
  './assets/furniture/pet-beds/petbed-gray.png',
  './assets/furniture/pet-beds/petbed-pink.png',
  './assets/furniture/pet-beds/petbed-red.png',
  './assets/furniture/rugs/rug-cloud-dark.png',
  './assets/furniture/rugs/rug-cloud-white.png',
  './assets/furniture/rugs/rug-heart-blue.png',
  './assets/furniture/rugs/rug-heart-dark.png',
  './assets/furniture/rugs/rug-heart-pink.png',
  './assets/furniture/rugs/rug-heart-white.png',
  './assets/furniture/shelves/shelf-brown.png',
  './assets/furniture/shelves/shelf-dark-brown.png',
  './assets/furniture/shelves/shelf-white.png',
  './assets/gifts/Bouquet.PNG',
  './assets/gifts/Bow.PNG',
  './assets/gifts/Bunny-ears.PNG',
  './assets/gifts/Cat-ears.PNG',
  './assets/gifts/Crown.PNG',
  './assets/gifts/Flower.PNG',
  './assets/gifts/Gaming-controller.PNG',
  './assets/gifts/Heart-locket.PNG',
  './assets/gifts/Jester-bell.PNG',
  './assets/gifts/Knife.PNG',
  './assets/gifts/Love-letter.PNG',
  './assets/gifts/Magical-girl-pendant.PNG',
  './assets/gifts/Mustache.PNG',
  './assets/gifts/Paint-brush.PNG',
  './assets/gifts/Party-hat.PNG',
  './assets/gifts/Pill.PNG',
  './assets/gifts/Pocket-monster-ball.PNG',
  './assets/gifts/Rings.PNG',
  './assets/gifts/Sleep-mask.PNG',
  './assets/gifts/Sunglasses.PNG',
  './assets/gifts/Teddy-bear.PNG',
  './assets/gifts/Top-hat.PNG',
  './assets/gifts/UFO.PNG',
  './assets/ingredients/Angel-wing.PNG',
  './assets/ingredients/bathtub.png',
  './assets/ingredients/eyebrows.png',
  './assets/ingredients/googly-eyes.png',
  './assets/ingredients/scarf.png',
  './assets/ingredients/skateboard.png',
  './assets/ingredients/vampire-teeth.png',
  './assets/ingredients/wig.png',
  './assets/ingredients/Demon-wing.PNG',
  './assets/ingredients/Ghost.PNG',
  './assets/ingredients/Hold2',
  './assets/ingredients/Moon.PNG',
  './assets/ingredients/Sparkle.PNG',
  './assets/ingredients/Thread.PNG',
  './assets/ingredients/Yarn.PNG',
  './assets/miko/Miko-angry.PNG',
  './assets/miko/Miko-bangs.PNG',
  './assets/miko/Miko-bangs-pinned.PNG',
  './assets/miko/Miko-Boxers.PNG',
  './assets/miko/Miko-big-shirt.PNG',
  './assets/miko/Miko-socks.PNG',
  './assets/miko/Miko-base-arm.PNG',
  './assets/miko/Miko-base.PNG',
  './assets/miko/Miko-belt.PNG',
  './assets/miko/Miko-button-shirt-closet.PNG',
  './assets/miko/Miko-button-shirt.PNG',
  './assets/miko/Miko-button-sleeve.PNG',
  './assets/miko/Miko-capri-pants.PNG',
  './assets/miko/Miko-hair.PNG',
  './assets/miko/Miko-happy.PNG',
  './assets/miko/Miko-headband.PNG',
  './assets/miko/Miko-hoodie-back.PNG',
  './assets/miko/Miko-hoodie-closet.PNG',
  './assets/miko/Miko-hoodie-sleeve.PNG',
  './assets/miko/Miko-hoodie.PNG',
  './assets/miko/Miko-jeans.PNG',
  './assets/miko/Miko-loafers.PNG',
  './assets/miko/Miko-neutral.PNG',
  './assets/miko/Miko-sad.PNG',
  './assets/miko/Miko-shocked.PNG',
  './assets/miko/Miko-smug.PNG',
  './assets/miko/Miko-sweater-closet.PNG',
  './assets/miko/Miko-sweater-sleeve.PNG',
  './assets/miko/Miko-sweater.PNG',
  './assets/miko/black-blazer.png',
  './assets/miko/black-blazer-shop.png',
  './assets/miko/black-blazer-arm-piece.png',
  './assets/miko/black-hairpins.png',
  './assets/miko/blouse.png',
  './assets/miko/fancy-loafers.png',
  './assets/miko/shorts.png',
  './assets/miko/white-garter-socks.png',
  './assets/oc-invitations/Miko-invitation.PNG',
  './assets/paint/Aqua-paint.PNG',
  './assets/paint/Black-paint.PNG',
  './assets/paint/Blue-paint.PNG',
  './assets/paint/Bronze-paint.PNG',
  './assets/paint/Dark-red-paint.PNG',
  './assets/paint/magenta-paint.png',
  './assets/paint/Gold-paint.PNG',
  './assets/paint/Green-paint.PNG',
  './assets/paint/Grey-paint.PNG',
  './assets/paint/Mint-paint.PNG',
  './assets/paint/Orange-paint.PNG',
  './assets/paint/Peach-paint.PNG',
  './assets/paint/Periwinkle-paint.PNG',
  './assets/paint/Pink-paint.PNG',
  './assets/paint/Purple-paint.PNG',
  './assets/paint/Rainbow-paint.PNG',
  './assets/paint/Red-paint.PNG',
  './assets/paint/Silver-paint.PNG',
  './assets/paint/Sky-blue-paint.PNG',
  './assets/paint/Violet-paint.PNG',
  './assets/paint/White-paint.PNG',
  './assets/peep/.keep',
  './assets/peep/bangs.png',
  './assets/peep/base.png',
  './assets/peep/beret.png',
  './assets/peep/bunny-tail.png',
  './assets/peep/cat-ears.png',
  './assets/peep/cheek-bandage.png',
  './assets/peep/collar.png',
  './assets/peep/colorful-sneakers.png',
  './assets/peep/cow-ears.png',
  './assets/peep/cow-tail.png',
  './assets/peep/cropped-jacket.png',
  './assets/peep/expression-happy.png',
  './assets/peep/expression-mad.png',
  './assets/peep/expression-neutral.png',
  './assets/peep/expression-sad.png',
  './assets/peep/expression-shocked.png',
  './assets/peep/fluffy-skirt.png',
  './assets/peep/hair-jellyfish.png',
  './assets/peep/hair-long-pigtails.png',
  './assets/peep/hair-low-pigtails.png',
  './assets/peep/hair-ponytail.png',
  './assets/peep/hair-short.png',
  './assets/peep/hair-side-ribbon.png',
  './assets/peep/horns.png',
  './assets/peep/large-back-hair-bow.png',
  './assets/peep/left-bow.png',
  './assets/peep/loafer-shoes.png',
  './assets/peep/off-shoulder-sweater.png',
  './assets/peep/pleated-skirt.png',
  './assets/peep/right-bow.png',
  './assets/peep/right-leg-bandage.png',
  './assets/peep/short-sleeved-shirt.png',
  './assets/peep/sock-left-blue.png',
  './assets/peep/sock-left-rainbow.png',
  './assets/peep/sock-right-blue.png',
  './assets/peep/sock-right-rainbow.png',
  './assets/peep/white-cardigan-sides.png',
  './assets/peep/white-cardigan-shop.png',
  './assets/peep/white-dress.png',
  './assets/peep/white-lace-stockings.png',
  './assets/peep/white-mary-janes.png',
  './assets/peep/white-bow.png',
  './assets/room-expansion/shelves/shelf-brown.png',
  './assets/room-expansion/shelves/shelf-cream.png',
  './assets/room-expansion/shelves/shelf-dark-brown.png',
  './assets/rooms/.keep',
  './assets/rooms/blue.png',
  './assets/rooms/chocolate-brown.png',
  './assets/rooms/cotton-candy.png',
  './assets/rooms/cream.png',
  './assets/rooms/dark-purple.png',
  './assets/rooms/green.png',
  './assets/rooms/peach.png',
  './assets/rooms/pink.png',
  './assets/rooms/purple.png',
  './assets/ui/.keep',
  './assets/ui/book-icon.png',
  './assets/ui/book-room.png',
  './assets/ui/mirror.png',
  './assets/ui/pink-coin.png',
  './bakery/index.html',
  './index.html',
  './manifest.webmanifest',
  './assets/furniture/pet-beds/Bed-white.PNG',
  './assets/furniture/pet-beds/Bed-red.PNG',
  './assets/furniture/pet-beds/Bed-dark-red.PNG',
  './assets/furniture/pet-beds/Bed-magenta.PNG',
  './assets/furniture/pet-beds/Bed-orange.PNG',
  './assets/furniture/pet-beds/Bed-peach.PNG',
  './assets/furniture/pet-beds/Bed-gold.PNG',
  './assets/furniture/pet-beds/Bed-silver.PNG',
  './assets/furniture/pet-beds/Bed-bronze.PNG',
  './assets/furniture/pet-beds/Bed-green.PNG',
  './assets/furniture/pet-beds/Bed-mint.PNG',
  './assets/furniture/pet-beds/Bed-aqua.PNG',
  './assets/furniture/pet-beds/Bed-sky-blue.PNG',
  './assets/furniture/pet-beds/Bed-blue.PNG',
  './assets/furniture/pet-beds/Bed-periwinkle.PNG',
  './assets/furniture/pet-beds/Bed-purple.PNG',
  './assets/furniture/pet-beds/Bed-violet.PNG',
  './assets/furniture/pet-beds/Bed-pink.PNG',
  './assets/furniture/pet-beds/Bed-grey.PNG',
  './assets/furniture/pet-beds/Bed-black.PNG',
  './assets/furniture/pet-beds/Bed-rainbow.PNG',
  './assets/furniture/lights/Lights-white.png',
  './assets/furniture/lights/Lights-red.png',
  './assets/furniture/lights/Lights-dark-red.png',
  './assets/furniture/lights/Lights-magenta.png',
  './assets/furniture/lights/Lights-orange.png',
  './assets/furniture/lights/Lights-peach.png',
  './assets/furniture/lights/Lights-gold.png',
  './assets/furniture/lights/Lights-silver.png',
  './assets/furniture/lights/Lights-bronze.png',
  './assets/furniture/lights/Lights-green.png',
  './assets/furniture/lights/Lights-mint.png',
  './assets/furniture/lights/Lights-aqua.png',
  './assets/furniture/lights/Lights-sky-blue.png',
  './assets/furniture/lights/Lights-blue.png',
  './assets/furniture/lights/Lights-periwinkle.png',
  './assets/furniture/lights/Lights-purple.png',
  './assets/furniture/lights/Lights-violet.png',
  './assets/furniture/lights/Lights-pink.png',
  './assets/furniture/lights/Lights-grey.png',
  './assets/furniture/lights/Lights-black.png',
  './assets/furniture/lights/Lights-rainbow.png',
  './script-v24-19.js',
  './style-v24-19.css'
];

self.addEventListener("install", event => {
  self.skipWaiting();
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    // Cache one-by-one so one unusual asset can never prevent the whole app
    // from becoming available offline.
    await Promise.allSettled(PRECACHE_URLS.map(url => cache.add(url)));
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys
      .filter(key => key.startsWith("duck-habit-hub-pwa-") && key !== CACHE_NAME)
      .map(key => caches.delete(key)));
    await self.clients.claim();
  })());
});

async function networkFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const response = await fetch(request);
    if (response && response.ok) await cache.put(request, response.clone());
    return response;
  } catch (error) {
    const cached = await cache.match(request, { ignoreSearch: true });
    if (cached) return cached;
    if (request.mode === "navigate") {
      return (await cache.match("./index.html")) || (await cache.match("./"));
    }
    throw error;
  }
}

async function staleWhileRevalidate(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request, { ignoreSearch: true });
  const fresh = fetch(request).then(async response => {
    if (response && response.ok) await cache.put(request, response.clone());
    return response;
  }).catch(() => null);

  return cached || (await fresh) || Response.error();
}

self.addEventListener("fetch", event => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  const extension = url.pathname.split('.').pop().toLowerCase();
  const isImageOrMedia = ["png","jpg","jpeg","webp","gif","svg","ico","mp3","wav","ogg","mp4","webm"].includes(extension);

  // Code/navigation is network-first so GitHub updates appear automatically
  // whenever the player is online. Cached copies are the offline fallback.
  event.respondWith(isImageOrMedia
    ? staleWhileRevalidate(request)
    : networkFirst(request));
});
